# Generated by Django 3.2 on 2021-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0002_auto_20210818_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respone',
            name='name',
            field=models.CharField(default='ANONYMOUS', max_length=128),
        ),
        migrations.AlterField(
            model_name='respone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(default='ANONYMOUS', max_length=128),
        ),
        migrations.AlterField(
            model_name='thread',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
