# Generated by Django 3.2 on 2021-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0003_auto_20210818_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respone',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
