# Generated by Django 3.2 on 2021-08-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0004_auto_20210818_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
