# Generated by Django 3.2 on 2021-08-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0005_auto_20210819_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respone',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
