# Generated by Django 3.2 on 2021-08-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0006_auto_20210819_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respone',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='thread',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
