# Generated by Django 4.0.4 on 2022-09-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=16)),
                ('is_nsfw', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Forumpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=128)),
                ('welcome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_desc', models.TextField()),
                ('report_status', models.CharField(max_length=16)),
                ('f_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chan.forumpost')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('forumpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chan.forumpost')),
                ('subject', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('poster', models.CharField(default='Anonymous', max_length=128)),
                ('is_sticky', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chan.board')),
            ],
            bases=('chan.forumpost',),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('forumpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chan.forumpost')),
                ('poster', models.TextField(default='Anonymous', max_length=128)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chan.thread')),
            ],
            bases=('chan.forumpost',),
        ),
    ]
